#MIW nodejs ex2
version: '2'
services:

    nodejs:
        container_name: miw_nodejs_ex2
        build: ./docker/nodejs_ex2
        working_dir: /var/www
        volumes:
          - ./ex2/:/var/www/
        ports:
          - "3000:3000"
          - "80:80"
        links:
          - mongodb
        networks:
          mynet:
            ipv4_address: 172.30.0.113

    mongodb:
        container_name: miw_mongodb
        build: ./docker/mongo
#        image: mongo
        environment:
            MONGODB_USER: root
            MONGODB_PASS: toor
            MONGODB_DB: "miwscrapper"
        volumes:
          - mongo-data:/var/lib/mongo
          - ./docker/mongo/data/:/var/www/data/
        ports:
            - "27017:27017"
        networks:
          mynet:
            ipv4_address: 172.30.0.114

volumes:
    mongo-data:
#        driver: local

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.1/24


