#MIW nodejs ex1
version: '2'
services:

    nodejs:
        container_name: miw_nodejs_ex1
        build: ./docker/nodejs_ex1
        working_dir: /var/www
        volumes:
          - ./ex1/:/var/www/
        ports:
          - "3000:3000"
          - "80:80"
        networks:
          mynet:
            ipv4_address: 172.30.0.113


networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.1/24


