
FROM node:7.7.1
MAINTAINER Jérémy BLONDEAU <jblondeau2@gmail.com>

ENV NODE_ENV production


RUN npm install -g babel
RUN npm install -g babel-cli
RUN npm install -g create-react-app
RUN npm install -g react-scripts


WORKDIR /var/www


EXPOSE 3000

