FROM mongo:latest

# Install mongo client
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN apt-get install -y mongodb-org-shell
RUN apt-get install -y mongodb-org-tools



#RUN mongo
#RUN mongo db.movie.insert({"name":"tutorials point"})

